name: kai-backend

on:
  push:
    paths:
      - "apps/backend/**"
    branches:
      - "**"
  pull_request:
    paths:
      - "apps/backend/**"
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: |
          mkdir -p ./apps/backend
          echo "AZURE_OPENAI_KEY=${{ vars.AZURE_OPENAI_KEY }}" >> ./apps/backend/.env
          echo "AZURE_OPENAI_ENDPOINT=${{ vars.AZURE_OPENAI_ENDPOINT }}" >> ./apps/backend/.env
          echo "AZURE_OPENAI_DEPLOMENT_ID=${{ vars.AZURE_OPENAI_DEPLOMENT_ID }}" >> ./apps/backend/.env
          echo "DATABASE_HOST=${{ vars.DATABASE_HOST }}" >> ./apps/backend/.env
          echo "DATABASE_PORT=${{ vars.DATABASE_PORT }}" >> ./apps/backend/.env
          echo "DATABASE_USER=${{ vars.DATABASE_USER }}" >> ./apps/backend/.env
          echo "DATABASE_PWD=${{ vars.DATABASE_PWD }}" >> ./apps/backend/.env
          echo "DATABASE_COLLECTION=${{ vars.DATABASE_COLLECTION }}" >> ./apps/backend/.env
          echo "KEY_CLOAK_URL=${{ vars.KEY_CLOAK_URL }}" >> ./apps/backend/.env
          echo "KEY_CLOAK_REALM=${{ vars.KEY_CLOAK_REALM }}" >> ./apps/backend/.env
          echo "KEY_CLOAK_CLIENT_ID=${{ vars.KEY_CLOAK_CLIENT_ID }}" >> ./apps/backend/.env
          echo "KEY_CLOAK_CLIENT_SECRET=${{ vars.KEY_CLOAK_CLIENT_SECRET }}" >> ./apps/backend/.env

      - name: Pre compilation
        run: npm run build

      # テスト成功時はこちらのステップが実行される
      - name: Slack Notification on Success at Testing Stage
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOKS }}
          SLACK_CHANNEL: github-actions
          SLACK_TITLE: Test Success
          SLACK_COLOR: good
          SLACK_FOOTER: "Powered by Yancey Inc. and its affiliates."

      # テスト失敗時はこちらのステップが実行される
      - name: Slack Notification on Failure at Testing Stage
        uses: rtCamp/action-slack-notify@v2
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOKS }}
          SLACK_CHANNEL: github-actions
          SLACK_TITLE: Test Failure
          SLACK_COLOR: danger
          SLACK_FOOTER: "Powered by Yancey Inc. and its affiliates."

  deployment:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: |
          mkdir -p ./apps/backend
          echo "VITE_SERVICE_URL=${{ vars.VITE_SERVICE_URL }}" >> ./apps/backend/.env
          echo "VITE_KEY_CLOAK_CLIENT_ID=${{ vars.VITE_KEY_CLOAK_CLIENT_ID }}" >> ./apps/backend/.env
          echo "VITE_KEY_CLOAK_REALM=${{ vars.VITE_KEY_CLOAK_REALM }}" >> ./apps/backend/.env
          echo "VITE_KEY_CLOAK_URL=${{ vars.VITE_KEY_CLOAK_URL }}" >> ./apps/backend/.env
          cd ./app/backend
          cat .env

      - name: Compilation
        run: |
          cd ./apps/backend
          npm run build

      - name: Prepare files for deployment
        run: |
          mkdir -p dist
          cp -r apps/backend/dist/* dist/

      - name: Copy file via ssh key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: "dist/*"
          target: "/var/www/kai-monorepo/apps/backend"
          overwrite: true

      - name: SSH to Server and Run Command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/kai-monorepo/apps/backend
            pm2 reload ecosystem.config.js

      # テスト成功時はこちらのステップが実行される
      - name: Slack Notification on Success at Deployment Stage
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOKS }}
          SLACK_CHANNEL: github-actions
          SLACK_TITLE: Deploy Success
          SLACK_COLOR: good
          SLACK_FOOTER: "Powered by Yancey Inc. and its affiliates."

      # テスト失敗時はこちらのステップが実行される
      - name: Slack Notification on Failure at Deployment Stage
        uses: rtCamp/action-slack-notify@v2
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOKS }}
          SLACK_CHANNEL: github-actions
          SLACK_TITLE: Deploy Failure
          SLACK_COLOR: danger
          SLACK_FOOTER: "Powered by Yancey Inc. and its affiliates."
